export const communityOverview = `MATCH (p:Person) OPTIONAL MATCH (p)-[:CAN_HELP_WITH]->(skill:Skill) WITH p, collect(skill.name) AS skills OPTIONAL MATCH (p)-[:WORKS_ON]->(project:Project) RETURN p.id AS id, p.name AS name, p.role AS role, p.location AS location, p.avatar AS avatar, p.availability AS availability, skills, collect(project.name) AS projects ORDER BY p.name`;

// A 3-hop traversal: person -> skill -> person -> project.
export const introductionsFor = `MATCH (me:Person {id: $personId})-[:WANTS_TO_LEARN]->(interest:Skill) MATCH (mentor:Person)-[:CAN_HELP_WITH]->(interest) WHERE mentor <> me OPTIONAL MATCH (mentor)-[:WORKS_ON]->(project:Project) WITH me, interest, mentor, collect(DISTINCT project.name) AS projects OPTIONAL MATCH path = (me)-[:KNOWS*1..3]-(mentor) WITH me, interest, mentor, projects, path ORDER BY length(path) WITH me, interest, mentor, projects, collect(path)[0] AS warmPath RETURN mentor.id AS id, mentor.name AS name, mentor.role AS role, mentor.location AS location, mentor.avatar AS avatar, mentor.availability AS availability, interest.name AS sharedSkill, projects, coalesce(length(warmPath), 4) AS socialDistance, CASE WHEN warmPath IS NULL THEN [me.name, mentor.name] ELSE [node IN nodes(warmPath) | node.name] END AS pathNames ORDER BY socialDistance, mentor.name LIMIT 12`;

// A multi-hop query revealing non-obvious project bridges.
export const projectBridges = `MATCH (from:Project {slug: $projectSlug})<-[:WORKS_ON]-(person:Person) MATCH (person)-[:KNOWS*1..2]-(bridge:Person)-[:WORKS_ON]->(to:Project) WHERE to <> from RETURN to.slug AS slug, to.name AS name, to.summary AS summary, to.stage AS stage, count(DISTINCT bridge) AS bridgeCount, collect(DISTINCT bridge.name)[0..3] AS bridgePeople ORDER BY bridgeCount DESC, name LIMIT 8`;

export const searchPeople = `MATCH (p:Person) OPTIONAL MATCH (p)-[:CAN_HELP_WITH]->(skill:Skill) WITH p, collect(toLower(skill.name)) AS skills WHERE toLower(p.name) CONTAINS toLower($term) OR toLower(p.role) CONTAINS toLower($term) OR any(skillName IN skills WHERE skillName CONTAINS toLower($term)) RETURN p.id AS id, p.name AS name, p.role AS role, p.location AS location, p.avatar AS avatar, p.availability AS availability, skills ORDER BY p.name LIMIT 20`;
